---
title: "Neural networks in R"
output:
  html_document: default
  html_notebook: default
---

Topics to cover:

* Background
* Single-layer networks
* Multi-layer networks
* Possibly more


Before we dig in, we will install the R packages we'll be using.

**R packages**
```{r}
# List of packages we will use.
packages = c("MASS", "nnet", "h2o", "devtools")

# Try to load each package and save the result.
success = sapply(packages, require, character.only = T, quietly = T)

# Check if any packages still need to be installed.
if (sum(!success) > 0) {
  # Install any needed packages.
  install.packages(packages[!success])
  
  # Load the newly installed packages.
  sapply(packages[!success], require, character.only = T, quietly = T)
}

github_packages = c(
  # Chris's tools package for plotting the SuperLearner.
  "ck37/ck37r",
  # Use more up-to-date SuperLearner from github.
  "ecpolley/SuperLearner")

devtools::install_github(github_packages)

# Clean up variables.
rm(packages, success, github_packages)
```

# Background



# Software packages



# Data preparation

```{r}
data(Boston, package = "MASS")

# Remove our outcome variable from the covariate list.
X_df = Boston[, -14]

# Convert X from a dataframe to a matrix.
X_mat = model.matrix(~ .,  data = X_df)

# Notice the extra intercept column added by model.matrix.
colnames(X_mat)
                 
#  Remove extra intercept term.
X_mat = X_mat[, -1]

# Regression (continuous) version of our outcome variable.
Y_reg = Boston$medv

# Review outcome distribution.
summary(Y_reg)

# Classification (binary) version of our outcome variable.
Y_class = as.factor(as.numeric(Boston$medv > 23))

# Review outcome distribution.
table(Y_class)
prop.table(table(Y_class))

```

